### ISSUE TITLE
no detected spatial_community

### ISSUE THREAD

**Issue by Elena983** [BodenmillerGroup/cytomapper#89]
Hello, I can't generate the spatial community values for spatial analysis.
Could you please check my sce object
[spe.rds.zip](https://github.com/BodenmillerGroup/cytomapper/files/14176928/spe.rds.zip)

**Comment by lassedochreden** [comment]
Hi @Elena983, 

the `cytomapper` package is developed for image visualization and not to perform spatial analysis. Please refer to the `imcRtools` package for related questions or issues. 

Furthermore, I am assuming that you are following the [IMCDataAnalysis](https://bodenmillergroup.github.io/IMCDataAnalysis/index.html) bookdown, since you opened a similar issue there. 

Will **close** this here. 

Please make sure to open an issue at the appropriate repository next time. Thanks in advance!
